services:
  pocketbase:
    container_name: pocketbase
    build: .
    image: pocketbase:latest
    init: true
    environment:
      - PORT=${PORT}
    volumes:
      - data:/app/data
    ports:
      - "${PORT}:${PORT}"

volumes:
  data:
